### ISSUE TITLE
Error: Cannot find module './server/server'

### ISSUE THREAD

**Issue by georgeedwards** [ericmdantas/generator-ng-fullstack#143] opened 2016-05-05 12:42 UTC
I am testing v1.8 and have created an app (Fullstack, Typescript, ng2, http2), but when I run `npm start`, I get the following error. It looks like the path isn't being rendered with `.js`? I'll look into it. 

```
npm start

> Gen-App@0.0.1 start C:\Users\George\Documents\GitHub\gen-app
> node index

module.js:341
    throw err;
    ^

Error: Cannot find module './server/server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\George\Documents\GitHub\gen-app\index.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by georgeedwards** [comment] 2016-05-05 12:51
OK, so `tsc` hadn't run, hence there was no server.js

**Comment by ericmdantas** [comment] 2016-05-05 14:09
Hey, @georgeedwards.

> So maybe that needs to be built into the toolchain

Yep.
```
"dev": "concurrently \"npm start\" \"gulp\"",
```
 it tries to start the server right away. We've got to know if the user is using Typescript (be it on server, client or both), so we compile first and do the rest later.

> Not sure why I am using babel with Typescript?

Babel is used in `gulpfile.babel.js`, so you can write `esNext` (es2015, es2016, etc) in your task files without having to explicitly compile.

About the last error, I'm trying to reproduce.

**Comment by ericmdantas** [comment] 2016-05-05 14:44
Couldn't reproduce it. Other than the `tsc` missing before starting the server, babel is working just fine in the tasks.

Do you happen to have any version of babel installed globally?

**Comment by ericmdantas** [comment] 2016-05-05 14:46
I'll close this one and open an issue specific about the compilation step.

But we can still discuss it here.

**Closed** 2016-05-05 14:47 UTC

**Comment by georgeedwards** [comment] 2016-05-05 15:13
no global babel installation.Interestingly, the exact same project, but without selecting the http2 option works fine...

**Comment by ericmdantas** [comment] 2016-05-05 15:25
shouldn't make a difference, though

**Comment by georgeedwards** [comment] 2016-05-05 15:30
well that's what I though, I wonder if there is a bug causing a file to be missed out or overwritten etc. with the http2 selection?

**Comment by ericmdantas** [comment] 2016-05-05 15:42
Very few things change when you select http/2. The main entry point for the server changes (it's a different file), and the `tasks/client/watch.js` changes from `http` to `https`. Nothing changes in the `package.json`.

**Comment by georgeedwards** [comment] 2016-05-05 15:44
hmm, I deleted all node_modules and did a clean install - all works! Not sure what that was.
