### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by jelling** [ericmdantas/generator-ng-fullstack#199] opened 2016-07-23 03:55 UTC
After running "npm install", I run "npm run dev" and I get the following error: 

> Error: Couldn't find preset "es2015" relative to directory"....

This happens despite running:

`npm install --save-dev babel-preset-es2015`

Other people had this issue with other projects so I tried their advice of deleting my node_modules in the project folder and also clearing the npm cache, but no luck. 

I'm using node v6.2.2 and npm 3.10.5.

Any ideas? I'm dead in the water.

**Comment by ericmdantas** [comment] 2016-07-23 13:09
Hello, @jelling.

I couldn't reproduce the problem, could you please provide the following info?

- Do you have babel installed globally? If so, what's the version?
-  What's the content of your `.yo-rc.json` (root of your app)?
- Have you tried to run `npm cache clean` and running `npm i` again?
- Can you check if you have any hidden `.babelrc` file in the parent folder?

**Comment by ericmdantas** [comment] 2016-07-26 00:31
Closing as it's an external bug, but feel free to let me know how it goes.

**Closed by ericmdantas** 2016-07-26 00:31 UTC
Labels: external-bug

**Comment by jelling** [comment] 2016-07-26 01:43
Thanks, Eric! I had a mysterious .babelrc file in the parent directory. Deleting it fixed the immediate issue.

**Comment by jelling** [comment] 2016-07-26 01:49
For anyone else having this issue, I then had to create a .babelrc folder in the project directory to use the es2005 presets. It looks like this:

`{
  "presets": ["es2015"]
}`

After that, the server started.

**Comment by ericmdantas** [comment] 2016-07-26 09:51
Awesome!
