### ISSUE TITLE
Only client install with angular2 (ng2) console error

### ISSUE THREAD

**Issue by isener** [ericmdantas/generator-ng-fullstack#163] opened 2016-06-09 08:38 UTC
I faced this error when only install client and type;

`npm start` -> in package.json script is `aliv` which I don't understand how it uses gulp config(like ts compile)

then I couldn't find what causes this exception;

http://prntscr.com/be72yq

Any kind of help is useful. Thanks.

**Comment by ericmdantas** [comment] 2016-06-09 10:28
Hello, @isener.

Did you run `typings install` and `tsc`?

**Comment by isener** [comment] 2016-06-09 10:33
Nope, didn't work that. (also we shouldn't type `tsc` before aliv, this case when we work on aliv mode, then make changes on code side, we always should have to type `tsc` all the time.

**Comment by ericmdantas** [comment] 2016-06-09 10:45
Right, but that'll depend on the IDE you're using.

Looking at it again, I recognize the error. This is because since you're using a client-only app and the client is trying to get the todos from the server, but there's no server, then you get a `404` and `aliv` serves the `index.html` file.

**Comment by ericmdantas** [comment] 2016-06-09 20:01
I'm going to close this since it's by design. But feel free to open an issue with a possible solution/improvement.

**Closed by ericmdantas** 2016-06-09 20:01 UTC
