### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by EmmanuelObo** [ericmdantas/generator-ng-fullstack#215] opened 2016-08-15 20:26 UTC
All of a sudden I'm getting the following errors in the console when I run npm run dev:

`zone.js?rev=@@hash:461 Unhandled Promise rejection: (SystemJS) Unexpected token <
    SyntaxError: Unexpected token <
        at Object.eval (http://localhost:5000/right-track/components/file-uploader-cmp.js:12:25)
        at eval (http://localhost:5000/right-track/components/file-uploader-cmp.js:157:4)
        at eval (http://localhost:5000/right-track/components/file-uploader-cmp.js:158:3)
    Evaluating http://localhost:5000/node_modules/ng2-file-upload.js
    Evaluating http://localhost:5000/right-track/components/file-uploader-cmp.js
    Evaluating http://localhost:5000/right-track/components/rightTrack.js
    Evaluating http://localhost:5000/index.js
    Error loading http://localhost:5000/index.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Unexpected token <(…)consoleError @ zone.js?rev=@@hash:461
zone.js?rev=@@hash:463 Error: Uncaught (in promise): Error: (SystemJS) Unexpected token <(…)`

It was literally working fine before and all of a sudden I start getting these errors. I tried to check if I changed anything in the main component but nothing. I even looked through the tasks and server side stuff, everything the same.

**Comment by ericmdantas** [comment] 2016-08-15 20:49
Weird..

Couple questions:
- Is your stack `client only` or `fullstack`?
- What's the content of dev-tools > network > file-uploader-cmp.js? Is it your index.html?
- How is your module being imported?

**Comment by EmmanuelObo** [comment] 2016-08-15 20:55
- My stack is fullstack.
- file-uploader-cmp.js is one of my Angular components, it's separate from index.html. It looks like this: 

`"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var core_1 = require('@angular/core');
var ng2_file_upload_1 = require('../../../../node_modules/ng2-file-upload');
var FileUploaderComponent = (function () {
    function FileUploaderComponent(element, fileUploadService, renderer) {
        this.isHover = false;
        this.inputs = ['allowedMimeType',
            'allowedFileType',
            'autoUpload',
            'isHTML5',
            'headers',
            'maxFileSize',
            'queueLimit',
            'removeAfterUpload',
            'url'
        ];
        this.uploaderOptions = {};
        this.multiple = true;
        this.element = element;
        this.fileUploadService = fileUploadService;
        this.renderer = renderer;
    }
    FileUploaderComponent.prototype.ngOnInit = function () {
        for (var _i = 0, _a = this.inputs; _i < _a.length; _i++) {
            var input = _a[_i];
            if (this[input]) {
                this.uploaderOptions[input] = this[input];
            }
        }
        this.fileUploadService.setOptions(this.uploaderOptions);
        this.multiple = (!this.queueLimit || this.queueLimit > 1);
    };
    FileUploaderComponent.prototype.onDrop = function (event) {
        this._preventAndStop(event);
        this.isHover = false;
        var transfer = this._getTransfer(event);
        if (!transfer) {
            return;
        }
        this.fileUploadService.addToQueue(transfer.files);
    };
    FileUploaderComponent.prototype.onDragOver = function (event) {
        this._preventAndStop(event);
        if (this.isHover) {
            return;
        }
        var transfer = this._getTransfer(event);
        if (!this._haveFiles(transfer.types)) {
            return;
        }
        this.isHover = true;
    };
    FileUploaderComponent.prototype.onDragLeave = function (event) {
        this._preventAndStop(event);
        if (event.currentTarget === this.element[0]) {
            return;
        }
        this.isHover = false;
    };
    FileUploaderComponent.prototype.onChange = function ($event) {
        this.fileUploadService.addToQueue($event.srcElement.files);
    };
    FileUploaderComponent.prototype._getTransfer = function (event) {
        return event.dataTransfer ? event.dataTransfer : event.originalEvent.dataTransfer;
    };
    FileUploaderComponent.prototype._preventAndStop = function (event) {
        event.preventDefault();
        event.stopPropagation();
    };
    FileUploaderComponent.prototype._haveFiles = function (types) {
        if (!types) {
            return false;
        }
        if (types.indexOf) {
            return types.indexOf('Files') !== -1;
        }
        else if (types.contains) {
            return types.contains('Files');
        }
        else {
            return false;
        }
    };
    __decorate([
        core_1.Input(), 
        __metadata('design:type', String)
    ], FileUploaderComponent.prototype, "url", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Number)
    ], FileUploaderComponent.prototype, "queueLimit", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Number)
    ], FileUploaderComponent.prototype, "maxFileSize", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Boolean)
    ], FileUploaderComponent.prototype, "autoUpload", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Array)
    ], FileUploaderComponent.prototype, "allowedMimeType", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Array)
    ], FileUploaderComponent.prototype, "allowedFileType", void 0);
    __decorate([
        core_1.Input(), 
        __metadata('design:type', Array)
    ], FileUploaderComponent.prototype, "headers", void 0);
    __decorate([
        core_1.HostBinding('class.hover'), 
        __metadata('design:type', Boolean)
    ], FileUploaderComponent.prototype, "isHover", void 0);
    __decorate([
        core_1.HostListener('drop', ['$event']), 
        __metadata('design:type', Function), 
        __metadata('design:paramtypes', [Object]), 
        __metadata('design:returntype', void 0)
    ], FileUploaderComponent.prototype, "onDrop", null);
    __decorate([
        core_1.HostListener('dragover', ['$event']), 
        __metadata('design:type', Function), 
        __metadata('design:paramtypes', [Object]), 
        __metadata('design:returntype', void 0)
    ], FileUploaderComponent.prototype, "onDragOver", null);
    __decorate([
        core_1.HostListener('dragleave', ['$event']), 
        __metadata('design:type', Function), 
        __metadata('design:paramtypes', [Object]), 
        __metadata('design:returntype', void 0)
    ], FileUploaderComponent.prototype, "onDragLeave", null);
    FileUploaderComponent = __decorate([
        core_1.Component({
            selector: 'file-uploader',
            providers: [ng2_file_upload_1.FileUploader],
            templateUrl: './right-track/templates/file-upload.html',
            styles: [':host {border:1px solid black; padding:59px;display: block;}' +
                    '.hover {border: 3px solid green; backgroud: black;}']
        }), 
        __metadata('design:paramtypes', [core_1.ElementRef, ng2_file_upload_1.FileUploader, core_1.Renderer])
    ], FileUploaderComponent);
    return FileUploaderComponent;
}());
exports.FileUploaderComponent = FileUploaderComponent;
`

_It's translated from the original .ts file._

- For the modules I have the file-uploader installed in node_modules and I'm using SystemJs.

**Comment by ericmdantas** [comment] 2016-08-15 21:16
Do you have the dep in `client/dev/config.js`? You'll have to add the path there, just like `@angular` and `rxjs`. Like in here: http://stackoverflow.com/a/36670005.

**Comment by EmmanuelObo** [comment] 2016-08-15 21:33
The problem isn't coming from the file-uploader component itself. Even if I exclude it I will still get the same errors. It's originating from index.js (the main bootstrap component). It's weird because I didn't mess with anything there and it was running well before.

I recently fixed the issue with npm run dev (#203 I think). But even then it was running well so I'm just confused as to what went wrong between run sessions.

**Comment by ericmdantas** [comment] 2016-08-15 22:24
Is `file-uploader` (not your component, the dep) being downloaded, though? 

It seems like you're getting an html from the server, that's what `Unexpected token < SyntaxError: Unexpected token...` says - that `<` usually is `<!doctype html...`.

One of the ways to fix that is to add the path to config.js, if you haven't done it yet.

**Comment by EmmanuelObo** [comment] 2016-08-17 15:05
yea, but instead I just removed the file-uploader all together to try and see if it would run without it. But now I started getting errors with npm run dev. It's saying that it fails at tsc && concurrently. I already did typings install and tsc.

**Comment by ericmdantas** [comment] 2016-08-17 15:34
Can you run the commands separately and show me the log, please? 

- `tsc` - check log;
- `npm start` - check log;
- `gulp` - check log.

Just so we can see where the error is coming from.

**Comment by EmmanuelObo** [comment] 2016-08-18 18:35
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\emmao_000\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v4.2.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error right-track@0.0.1 dev: `tsc && concurrently "npm start" "gulp"`
22 error Exit status 1
23 error Failed at the right-track@0.0.1 dev script 'tsc && concurrently "npm start" "gulp"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the right-track package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm start" "gulp"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs right-track
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls right-track
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ericmdantas** [comment] 2016-08-18 18:39
And what does it log on the terminal?

**Comment by EmmanuelObo** [comment] 2016-08-18 18:49
This is actually what is logged in the terminal as well. I just copied it from the npm-debug log

**Comment by ericmdantas** [comment] 2016-08-18 19:21
Welp, that doesn't help much.

Could you try with a newer version of node? Your npm version is already one of the latest, but node is a bit old.

**Comment by EmmanuelObo** [comment] 2016-08-19 00:55
Yea I have the latest version of node and npm. Can't seem to understand this error.
But it doesn't seem like it is within the scope of this project so I'll keep checking for solutions.

**Comment by ericmdantas** [comment] 2016-08-19 01:02
Cool, cool. I'm trying to see what could be causing that too.

**Comment by amiral84** [comment] 2016-10-22 14:28
I got the same error when I tried to import json file. Because es6 doesn't have json support by default you can do it via webpack for example, but since this version (1.8.33) doesn't have webpack yet you must to configure it on yourself if you want.

**Comment by ericmdantas** [comment] 2017-04-28 10:59
Closing as I can't reproduce it.

**Closed by ericmdantas** 2017-04-28 10:59 UTC
Labels: angular 2.x, bug, client, systemjs
