### ISSUE TITLE
v1.1.0 Errors

### ISSUE THREAD

**Issue by jgodi** [ericmdantas/generator-ng-fullstack#12] opened 2015-04-13 12:16 UTC
I saw this from the other full stack generator and wanted to try it out (great work!). After installing everything and running the command: 

`yo ng-fullstack`

It errored out at:

```
AssertionError: /usr/local/lib/node_modules/generator-ng-fullstack/app/templates/.gitignore doesn't exist
```

The v1.1.0 release doesn't have the `.gitignore` file in the templates. Do you mind pushing a new release? 

Also, what are you thoughts and ideas on this? I would love to contribute and use this more!

**Comment by ericmdantas** [comment] 2015-04-13 14:27
Hello, @jgodi - thanks :D

That's a weird error, I'll try to reproduce it and I might push a new release today with the fix.

About the ideas: they're still floating around, I have a bunch of things to try out and include here, most of them I'm studying and checking the pros/cons, but I'm definetely open for new ideas - so, feel free to share them.

Just so you have an idea, I'm thinking about having an option to use [go](https://github.com/golang/go) on server side, it'd be a different stack/language, for now, I've been trying it out - and it feels great.

Right now I'm checking the best frameworks for webservice, mongodb's driver, coding best practices, etc.

**Comment by jgodi** [comment] 2015-04-13 14:32
That would be cool. We were initially going to use go for our backend on a new project, but ended up going with node just because the ease of the old generator.

Tonight I will play around with the generator and see if there are any things I can do with the gulp builds or anything once I get it working.

Thanks!

**Comment by ericmdantas** [comment] 2015-04-13 14:40
That's nice, turns out I'll have someone to check what I'm doing with the go code then :smile: .

Alright, so I managed to simulate the error at work (installing and running ```yo ng-fullstack```). The error doesn't happen when using ```npm link``` (working at home).

I'm looking into it.

**Comment by ericmdantas** [comment] 2015-04-13 14:46
Well, looks like there are more people with this issue: https://github.com/sindresorhus/generator-nm/issues/3

They might be trying to make it work with [this commit](https://github.com/sindresorhus/generator-nm/commit/01eb1d547faa1ff3a4808390c164f8918be9b01e)

I'll give it a try later today.

**Comment by ericmdantas** [comment] 2015-04-13 21:34
I'll let it open until installation of 1.1.1 is ok.

Gonna release it now.

**Comment by ericmdantas** [comment] 2015-04-13 21:38
Alright, version ```1.1.1``` is out.

Could @jgodi and @justingreenberg please update give it a try to run ```yo ng-fullstack```?

Thanks!

**Comment by jgodi** [comment] 2015-04-13 21:38
Yes, I will try tonight

**Comment by justingreenberg** [comment] 2015-04-13 21:47
updated npm module to `1.1.1` — `yo ng-fullstack` is working as expected :smile:

**Comment by ericmdantas** [comment] 2015-04-13 22:00
Thanks, @justingreenberg! Good job =]

Just waiting on @jgodi - no rush :smile: .

**Comment by jgodi** [comment] 2015-04-14 00:09
Works for me too. Thanks!

**Comment by ericmdantas** [comment] 2015-04-14 00:43
Alright, closing this.

Thanks, guys!

**Closed by ericmdantas** 2015-04-14 00:43 UTC
Labels: bug
